# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzQ4NTRjOTIxYjk0MzkwODVmNmY1ZjUwNzc0MDgyYTNkZGI3ZmIxNjE3NmQ1NjIyMDNjN2UzZTM4NzA4OGMyMjBkZjY2MGVlNDgzMzg1OWRjYzI4YzllMDljYjIwOTI4MDg4NjA3MGY1NzJjMzUwNjBkNjJkYzJkNTE0MDdlYWQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
